name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Инициализировать окружение
      run: make cp-env-test

    - name: Создание docker-compose.yml
      run: make cp-docker-compose

    - name: Запуск docker-compose
      run: make run

    - name: Валидация composer.json и composer.lock
      run: composer validate

    - name: Установить зависимости
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Права для кеша test
      run: mkdir -p var/cache/test && chmod 777 var/cache/test

    - name: Чистка кеша
      run: make cc-test

    - name: Запустить тесты
      run: make test
