name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Инициализировать окружение
      run: make cp-env-test

    - name: Создание docker-compose.yml
      run: make cp-docker-compose

    - name: Запуск docker-compose
      run: make run

    - name: Валидация composer.json и composer.lock
      run: docker-compose exec -T php-fpm /bin/sh -c "composer validate"

    - name: Установить зависимости
      run: docker-compose exec -T php-fpm /bin/sh -c "composer install --prefer-dist --no-progress --no-suggest"

    - name: Чистка кеша
      run: docker-compose exec -T php-fpm /bin/sh -c "make cc-test"

    - name: Запустить тесты
      run: docker-compose exec -T php-fpm /bin/sh -c "make test"
